--- #YAML:1.0
name: DateTime-Format-Bork
version: 0.01
license: perl
distribution_type: module
requires:
  DateTime: 0
  DateTime::Format::Builder: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  DateTime::Format::Bork:
    file: lib/DateTime/Format/Bork.pm
    version: 0.01
generated_by: Module::Build version 0.18
